package com.example.architecture_components_base_setup.room.daos

import androidx.room.Delete
import androidx.room.Insert
import androidx.room.Update


/*
Interface used to define database interactions;
Creates layer between app and database; recommended to avoid
making database queries/transactions directly from the app code
Class implementation will be generated by Room
at compile time.
 */


interface BaseDao<T> {
    @Insert
    fun insertAll(vararg obj: T)

    @Delete
    fun deleteAll(vararg obj: T)

    @Update
    fun updateAll(vararg obj: T)
}